"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.rss_channel_image import RssChannelImage

from deutschland import nina


class TestRssChannelImage(unittest.TestCase):
    """RssChannelImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRssChannelImage(self):
        """Test RssChannelImage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RssChannelImage()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
