"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.covid_map_style import CovidMapStyle

from deutschland import nina

globals()["CovidMapStyle"] = CovidMapStyle
from deutschland.nina.model.covid_map_data import CovidMapData


class TestCovidMapData(unittest.TestCase):
    """CovidMapData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCovidMapData(self):
        """Test CovidMapData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CovidMapData()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
