"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.faq import FAQ

from deutschland import nina

globals()["FAQ"] = FAQ
from deutschland.nina.model.faq_collection import FAQCollection


class TestFAQCollection(unittest.TestCase):
    """FAQCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFAQCollection(self):
        """Test FAQCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FAQCollection()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
