"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.archive_warning_history_history_inner import (
    ArchiveWarningHistoryHistoryInner,
)

from deutschland import nina

globals()["ArchiveWarningHistoryHistoryInner"] = ArchiveWarningHistoryHistoryInner
from deutschland.nina.model.archive_warning_history import ArchiveWarningHistory


class TestArchiveWarningHistory(unittest.TestCase):
    """ArchiveWarningHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArchiveWarningHistory(self):
        """Test ArchiveWarningHistory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ArchiveWarningHistory()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
