"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.covid_infos_category import CovidInfosCategory

from deutschland import nina

globals()["CovidInfosCategory"] = CovidInfosCategory
from deutschland.nina.model.covid_infos import CovidInfos


class TestCovidInfos(unittest.TestCase):
    """CovidInfos unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCovidInfos(self):
        """Test CovidInfos"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CovidInfos()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
