"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.ags_covid_rules_rules_inner_icon import (
    AGSCovidRulesRulesInnerIcon,
)

from deutschland import nina


class TestAGSCovidRulesRulesInnerIcon(unittest.TestCase):
    """AGSCovidRulesRulesInnerIcon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAGSCovidRulesRulesInnerIcon(self):
        """Test AGSCovidRulesRulesInnerIcon"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AGSCovidRulesRulesInnerIcon()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
