"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.ags_covid_rules_common_inner import AGSCovidRulesCommonInner
from deutschland.nina.model.ags_covid_rules_level import AGSCovidRulesLevel
from deutschland.nina.model.ags_covid_rules_regulations import AGSCovidRulesRegulations
from deutschland.nina.model.ags_covid_rules_rules_inner import AGSCovidRulesRulesInner

from deutschland import nina

globals()["AGSCovidRulesCommonInner"] = AGSCovidRulesCommonInner
globals()["AGSCovidRulesLevel"] = AGSCovidRulesLevel
globals()["AGSCovidRulesRegulations"] = AGSCovidRulesRegulations
globals()["AGSCovidRulesRulesInner"] = AGSCovidRulesRulesInner
from deutschland.nina.model.ags_covid_rules import AGSCovidRules


class TestAGSCovidRules(unittest.TestCase):
    """AGSCovidRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAGSCovidRules(self):
        """Test AGSCovidRules"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AGSCovidRules()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
