"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.ars_covid_rules_regulations_sections import (
    ARSCovidRulesRegulationsSections,
)

from deutschland import nina

globals()["ARSCovidRulesRegulationsSections"] = ARSCovidRulesRegulationsSections
from deutschland.nina.model.ars_covid_rules_regulations import ARSCovidRulesRegulations


class TestARSCovidRulesRegulations(unittest.TestCase):
    """ARSCovidRulesRegulations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testARSCovidRulesRegulations(self):
        """Test ARSCovidRulesRegulations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ARSCovidRulesRegulations()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
