"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.ars_covid_rules_common_inner import ARSCovidRulesCommonInner
from deutschland.nina.model.ars_covid_rules_level import ARSCovidRulesLevel
from deutschland.nina.model.ars_covid_rules_regulations import ARSCovidRulesRegulations
from deutschland.nina.model.ars_covid_rules_rules_inner import ARSCovidRulesRulesInner

from deutschland import nina

globals()["ARSCovidRulesCommonInner"] = ARSCovidRulesCommonInner
globals()["ARSCovidRulesLevel"] = ARSCovidRulesLevel
globals()["ARSCovidRulesRegulations"] = ARSCovidRulesRegulations
globals()["ARSCovidRulesRulesInner"] = ARSCovidRulesRulesInner
from deutschland.nina.model.ars_covid_rules import ARSCovidRules


class TestARSCovidRules(unittest.TestCase):
    """ARSCovidRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testARSCovidRules(self):
        """Test ARSCovidRules"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ARSCovidRules()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
