"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.notfalltipps_tip import NotfalltippsTip

from deutschland import nina

globals()["NotfalltippsTip"] = NotfalltippsTip
from deutschland.nina.model.notfalltipps_category import NotfalltippsCategory


class TestNotfalltippsCategory(unittest.TestCase):
    """NotfalltippsCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotfalltippsCategory(self):
        """Test NotfalltippsCategory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotfalltippsCategory()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
