"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.logo import Logo

from deutschland import nina


class TestLogo(unittest.TestCase):
    """Logo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogo(self):
        """Test Logo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Logo()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
