"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.ars_covid_rules_regulations_sections_bund_icon import (
    ARSCovidRulesRegulationsSectionsBUNDIcon,
)

from deutschland import nina


class TestARSCovidRulesRegulationsSectionsBUNDIcon(unittest.TestCase):
    """ARSCovidRulesRegulationsSectionsBUNDIcon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testARSCovidRulesRegulationsSectionsBUNDIcon(self):
        """Test ARSCovidRulesRegulationsSectionsBUNDIcon"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ARSCovidRulesRegulationsSectionsBUNDIcon()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
