"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.nina.api.default_api import DefaultApi  # noqa: E501

from deutschland import nina


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_data_version(self):
        """Test case for get_data_version

        Liefert die Versionsnummer.  # noqa: E501
        """
        pass

    def test_get_event_code(self):
        """Test case for get_event_code

        Event Code Bilddateien.  # noqa: E501
        """
        pass

    def test_get_event_codes(self):
        """Test case for get_event_codes

        Liefert Event Codes und Name der Bilddateien.  # noqa: E501
        """
        pass

    def test_get_faqs(self):
        """Test case for get_faqs

        FAQs  # noqa: E501
        """
        pass

    def test_get_logo(self):
        """Test case for get_logo

        Logo-Bilddateien.  # noqa: E501
        """
        pass

    def test_get_logos(self):
        """Test case for get_logos

        Liefert Namen und Logos für Sender-IDs  # noqa: E501
        """
        pass

    def test_get_notfalltipps(self):
        """Test case for get_notfalltipps

        Notfalltipps  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
