"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.ars_covid_rules_common_inner import ARSCovidRulesCommonInner

from deutschland import nina


class TestARSCovidRulesCommonInner(unittest.TestCase):
    """ARSCovidRulesCommonInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testARSCovidRulesCommonInner(self):
        """Test ARSCovidRulesCommonInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ARSCovidRulesCommonInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
