"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.event_code import EventCode

from deutschland import nina


class TestEventCode(unittest.TestCase):
    """EventCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventCode(self):
        """Test EventCode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EventCode()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
