"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.notfalltipps_article import NotfalltippsArticle

from deutschland import nina

globals()["NotfalltippsArticle"] = NotfalltippsArticle
from deutschland.nina.model.notfalltipps_tip import NotfalltippsTip


class TestNotfalltippsTip(unittest.TestCase):
    """NotfalltippsTip unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotfalltippsTip(self):
        """Test NotfalltippsTip"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotfalltippsTip()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
