"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.key_value_array_inner import KeyValueArrayInner

from deutschland import nina

globals()["KeyValueArrayInner"] = KeyValueArrayInner
from deutschland.nina.model.key_value_array import KeyValueArray


class TestKeyValueArray(unittest.TestCase):
    """KeyValueArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeyValueArray(self):
        """Test KeyValueArray"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KeyValueArray()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
