"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.key_value_array import KeyValueArray
from deutschland.nina.model.warning_info_inner_area_inner import (
    WarningInfoInnerAreaInner,
)

from deutschland import nina

globals()["KeyValueArray"] = KeyValueArray
globals()["WarningInfoInnerAreaInner"] = WarningInfoInnerAreaInner
from deutschland.nina.model.warning_info_inner import WarningInfoInner


class TestWarningInfoInner(unittest.TestCase):
    """WarningInfoInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWarningInfoInner(self):
        """Test WarningInfoInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WarningInfoInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
