"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.covid_infos_image import CovidInfosImage
from deutschland.nina.model.covid_infos_tip import CovidInfosTip

from deutschland import nina

globals()["CovidInfosImage"] = CovidInfosImage
globals()["CovidInfosTip"] = CovidInfosTip
from deutschland.nina.model.covid_infos_category import CovidInfosCategory


class TestCovidInfosCategory(unittest.TestCase):
    """CovidInfosCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCovidInfosCategory(self):
        """Test CovidInfosCategory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CovidInfosCategory()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
