"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.covid_map_data import CovidMapData
from deutschland.nina.model.covid_map_legend import CovidMapLegend

from deutschland import nina

globals()["CovidMapData"] = CovidMapData
globals()["CovidMapLegend"] = CovidMapLegend
from deutschland.nina.model.covid_map import CovidMap


class TestCovidMap(unittest.TestCase):
    """CovidMap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCovidMap(self):
        """Test CovidMap"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CovidMap()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
