"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.rss_channel_image import RssChannelImage
from deutschland.nina.model.rss_channel_item_inner import RssChannelItemInner

from deutschland import nina

globals()["RssChannelImage"] = RssChannelImage
globals()["RssChannelItemInner"] = RssChannelItemInner
from deutschland.nina.model.rss_channel import RssChannel


class TestRssChannel(unittest.TestCase):
    """RssChannel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRssChannel(self):
        """Test RssChannel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RssChannel()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
