"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.nina.api.archive_api import ArchiveApi  # noqa: E501

from deutschland import nina


class TestArchiveApi(unittest.TestCase):
    """ArchiveApi unit test stubs"""

    def setUp(self):
        self.api = ArchiveApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_full_warning_history(self):
        """Test case for get_full_warning_history

        Gesammelter Verlauf einer MOWAS Warnung  # noqa: E501
        """
        pass

    def test_get_warning_history(self):
        """Test case for get_warning_history

        Abruf einer archivierten MOWAS Warnung  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
