"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.ags_covid_rules_icon import AGSCovidRulesIcon

from deutschland import nina

globals()["AGSCovidRulesIcon"] = AGSCovidRulesIcon
from deutschland.nina.model.ags_covid_rules_rules import AGSCovidRulesRules


class TestAGSCovidRulesRules(unittest.TestCase):
    """AGSCovidRulesRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAGSCovidRulesRules(self):
        """Test AGSCovidRulesRules"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AGSCovidRulesRules()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
