"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.ags_covid_rules_regulations_sections_kreis_icon import (
    AGSCovidRulesRegulationsSectionsKREISIcon,
)

from deutschland import nina

globals()[
    "AGSCovidRulesRegulationsSectionsKREISIcon"
] = AGSCovidRulesRegulationsSectionsKREISIcon
from deutschland.nina.model.ags_covid_rules_regulations_sections_kreis import (
    AGSCovidRulesRegulationsSectionsKREIS,
)


class TestAGSCovidRulesRegulationsSectionsKREIS(unittest.TestCase):
    """AGSCovidRulesRegulationsSectionsKREIS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAGSCovidRulesRegulationsSectionsKREIS(self):
        """Test AGSCovidRulesRegulationsSectionsKREIS"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AGSCovidRulesRegulationsSectionsKREIS()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
