"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.covid_map_style import CovidMapStyle

from deutschland import nina

globals()["CovidMapStyle"] = CovidMapStyle
from deutschland.nina.model.covid_map_legend import CovidMapLegend


class TestCovidMapLegend(unittest.TestCase):
    """CovidMapLegend unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCovidMapLegend(self):
        """Test CovidMapLegend"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CovidMapLegend()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
