"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.nina.model.ars_covid_rules_regulations_sections_land_icon import (
    ARSCovidRulesRegulationsSectionsLANDIcon,
)

from deutschland import nina


class TestARSCovidRulesRegulationsSectionsLANDIcon(unittest.TestCase):
    """ARSCovidRulesRegulationsSectionsLANDIcon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testARSCovidRulesRegulationsSectionsLANDIcon(self):
        """Test ARSCovidRulesRegulationsSectionsLANDIcon"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ARSCovidRulesRegulationsSectionsLANDIcon()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
